apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mb-k8s.fullname" . }}
  labels:
    {{- include "mb-k8s.labels" . | nindent 4 }}
spec:
  parallelism: {{ default "1" .Values.jobParallelism }}
  backoffLimit: 0
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mb-k8s.serviceAccountName" . }}
      securityContext:
        sysctls:
          - name: net.ipv4.ip_local_port_range
            value: "1024 65535"
      restartPolicy: OnFailure
      volumes:
        {{- if .Values.app.storeOutput }}
        - name: temp-volume
          emptyDir: {}
        {{- end }}
        - name: mb-request-file
          configMap:
            name: {{ required "Missing app.requestConfigMap" .Values.app.requestConfigMap }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{- if .Values.image.tag -}}{{ .Values.image.tag }}{{- else -}}{{ .Chart.AppVersion }}{{- end -}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{- if .Values.app.storeOutput }}
            - name: temp-volume
              mountPath: /temp-dir
            {{- end }}
            - name: mb-request-file
              mountPath: /opt/request-file.json
              subPath: request-file.json
          env:
            {{- if .Values.app.storeOutput }}
            - name: STORE_OUTPUT
              value: "yes"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "mb-k8s.fullname" .) .Values.app.awsSecretName }}
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "mb-k8s.fullname" .) .Values.app.awsSecretName }}
                  key: secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "{{ required "missing app.awsDefaultRegion" .Values.app.awsDefaultRegion }}"
            - name: S3_BUCKET_NAME
              value: "{{ required "missing app.s3BucketName" .Values.app.s3BucketName }}"
            - name: TEMP_DIR
              value: "/temp-dir"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
             {{- end }}
            - name: REQUEST_FILE
              value: "/opt/request-file.json"
            - name: DURATION
              value: "{{ required "missing app.duration" .Values.app.duration }}"
            - name: RAMP_UP
              value: "{{ default "0" .Values.app.rampUp }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
